### ISSUE TITLE
Installation instructions for Linux

### ISSUE THREAD

**Issue by ddska** [Argent77/A7-BagsOfTorment#1]
Could you provide installation instructions for Linux, please?
The readme suggests to run `setup-BagsOfTorment.exe`, which is for Windows.
Thanks.

**Comment by Argent77** [comment]
Installation on Linux is basically the same as on Windows or macOS. However, mods usually don't provide extra packages for Linux because:
a) It required to create separate 32-bit and 64-bit packages (in the past). Latest WeiDU installer is 64-bit only though.
b) Most players seem to install mods by using a global `weidu` and `weinstall` binary in their path.

The WeiDU binary can be downloaded here: https://github.com/WeiDUorg/weidu/releases/latest

For option **a)** unpack the `weidu` binary from the zip archive, rename it to `setup-BagsOfTorment` and place it into the root folder of the game. Run the binary and follow the prompts to install the mod.

For option **b)** unpack both `weidu` and `weinstall` binaries and place them into `/usr/bin`, `$HOME/bin` or any other location which is included in your PATH. Go to the root folder of the game and call `weinstall BagsOfTorment`.

The latter option is probably less complicated since you only have to set it up once. Afterwards it can be used for any mods you want to install.

**Important:** A prerequisite for modding the game on Linux is that the filesystem must be made case-insensitive. There is a topic providing several methods how to do it (scroll further down for more options): https://www.gibberlings3.net/forums/topic/28516-the-linux-users-guide-to-installing-mods-on-the-enhanced-editions/

**Comment by ddska** [comment]
@Argent77 thank you very much for the detailed instructions! Please consider including them in the readme.
